title: PSWE-G3
description: Dokumentation für das PSWE-Praktikum
theme: just-the-docs
url: https://sturmcamper.github.io/PSWE-Docs
color_scheme: dark
callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: yellow
  warning:
    title: Warning
    color: red
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false
