title: PSWE-Doc
description: Praktikum Docs
theme: just-the-docs

url: https://sturmcamper.github.io/PSWE-Doc

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
